import Image from "next/image";
import useTrans from "../../hooks/useTrans";
import get from 'lodash.get';
import Head from "next/head";
import Link from "next/link";
import useWindowScroll from "../../hooks/useWindowScroll";
import useWindowSize from "../../hooks/useWindowSize";
import {Icon} from "../Icon";
import {useState} from "react";


export const HomeLayout = ({children}) => {
  const trans = useTrans();
  const yOffset = useWindowScroll();
  const {width} = useWindowSize();
  const [activeTag, setActiveTag] = useState('');

  const listMenu = [
    {
      label: 'introduce',
      children: [],
      url: ''
    },
    {
      label: 'warrantyPolicy',
      children: [],
      url: ''
    },
    {
      label: 'serviceCenter',
      children: [],
      url: ''
    },
    {
      label: 'appLC',
      children: [],
      url: ''
    },
    {
      label: 'support',
      children: [],
      url: ''
    },
  ];

  return (
    <div className={`font-sfprotext flex flex-col min-h-screen`}>
      <Head>
        <title>AIO</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/logo.svg"/>
      </Head>
      {width < 1024 ? <div className="drawer drawer-end">
          <input id="header-drawer" type="checkbox" className="drawer-toggle"/>
          <div className="drawer-content">
            <div className={`navbar bg-base-100 fixed z-10
      ${yOffset < 60 ? 'h-[102px] shadow-none' : 'h-[82px] shadow-header header-bg'} 
      transition-height duration-300 ease-in-out`}>
              <div className="flex-1">
                <a className="btn btn-ghost normal-case text-xl" href='/'>
                  <Image src={'/logo.svg'} width={81} height={50}/>
                </a>
              </div>
              <label htmlFor="header-drawer" className="drawer-button">
                <Icon icon={'menu'}/>
              </label>

            </div>
            <div className="flex-1">
              {children}
            </div>
          </div>
          <div className="drawer-side">
            <label htmlFor="header-drawer" className="drawer-overlay"></label>
            <div className="bg-white">
              <div className="flex justify-end items-center p-4">
                <label htmlFor="header-drawer">
                  <Icon icon={'close'} className="fill-black cursor-pointer"/>
                </label>
              </div>
              <ul className="menu p-4 w-80 bg-base-100 text-base-content">
                {listMenu.map((item) => item?.children.length <= 0
                  ? (
                    <li
                      className={`cursor-pointer ${activeTag === item.label ? 'active' : ''}`}
                      onClick={() => setActiveTag(item.label)}
                    >
                      <Link href={item.url}>
                        <div className='leading-normal text-[18px] font-bold'>{get(trans.home, item.label)}</div>
                      </Link>
                    </li>
                  ) : (
                    <li tabIndex={0}>
                      <a>
                        Parent
                        <svg className="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                             viewBox="0 0 24 24">
                          <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/>
                        </svg>
                      </a>
                      <ul className="p-2 bg-base-100">
                        <li><a>Submenu 1</a></li>
                        <li><a>Submenu 2</a></li>
                      </ul>
                    </li>
                  )
                )}
              </ul>
            </div>
          </div>
        </div>
        : <div className="flex flex-col">
          <div className={`navbar bg-base-100 fixed z-10
      ${yOffset < 60 ? 'h-[102px] shadow-none' : 'h-[82px] shadow-header header-bg'} 
      transition-height duration-300 ease-in-out`}>
            <div className="flex-1">
              <a className="btn btn-ghost normal-case text-xl" href='/'>
                <Image src={'/logo.svg'} width={91} height={59}/>
              </a>
            </div>
            <div className="flex-none">
              <ul className={`flex space-x-4 lg:space-x-8 px-1`}>
                {listMenu.map((item) => item?.children.length <= 0
                  ? (
                    <li className="cursor-pointer">
                      <Link href={item.url}>
                        <div className='leading-normal text-[18px] font-bold'>{get(trans.home, item.label)}</div>
                      </Link>
                    </li>
                  ) : (
                    <li tabIndex={0}>
                      <a>
                        Parent
                        <svg className="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                             viewBox="0 0 24 24">
                          <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/>
                        </svg>
                      </a>
                      <ul className="p-2 bg-base-100">
                        <li><a>Submenu 1</a></li>
                        <li><a>Submenu 2</a></li>
                      </ul>
                    </li>
                  )
                )}
              </ul>
            </div>
          </div>
          <div className="flex-1">
            {children}
          </div>
        </div>}
      <footer className="flex w-full items-center justify-center border-t bg-[#EE0033] py-16 space-y-2 lg:space-x-24 flex-col lg:flex-row">
        <a
          className="flex items-center justify-center gap-2"
          href="/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image src="/logo_footer.png" alt="AIO Logo" width={176} height={113}/>
        </a>
        <div className="flex flex-col space-y-2 text-white">
          <div className="inline-flex"><div className="font-semibold mr-1">Địa chỉ:</div> Số 6 Phạm Văn Bạch, Phường Yên Hòa, Quận Cầu Giấy, TP Hà Nội</div>
          <div className="inline-flex"><div className="font-semibold mr-1">Địa chỉ:</div> Số 6 Phạm Văn Bạch, Phường Yên Hòa, Quận Cầu Giấy, TP Hà Nội</div>
          <div className="inline-flex"><div className="font-semibold mr-1">Website:</div> www.congtrinhviettel.com.vn / www.viettelcontruction.com.vn</div>
        </div>
      </footer>
    </div>
  );
}